- restore_cache:
    keys:
    - v1-dependencies-{{ checksum "build.gradle" }}
    - v1-dependencies-
- run: gradle dependencies
- save_cache:
    paths:
      - ~/.gradle
    key: v1-dependencies-{{ checksum "build.gradle" }}